# Site settings
title: Toni
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://toni1234321.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Toni
user_description:
user_title: Experienced in: Pawn, C++, JS, HTML, SQL, Python and more.
email: none@gamil.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
